backend:
  name: github
  repo: sallynorthmore/think-climate
  branch: master # TODO: change this to master once we go live
#   auth_type: implicit
#   app_id: 43c25021ee0461cd3c4a3389671fbe266f6943c586fc24198aeedf2132427407

media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - label: 'Global site information'
    name: 'global'
    files:
      - label: 'Global site information'
        name: 'global'
        file: 'content/global.md'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'global',
            }
          - { label: Site Title, name: title, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Description, name: description, widget: string }
  - label: 'Subscribe'
    name: 'subscribe'
    files:
      - label: 'Subscribe'
        name: 'subscribe'
        file: 'content/subscribe.md'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'subscribe',
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home page'
        name: 'home'
        file: 'content/home.md'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'home-page',
            }
          - { label: Title, name: title, widget: string }
          - label: Hero
            name: hero
            widget: object
            fields:
              - {
                  label: Background Color (a hex value),
                  name: background,
                  widget: string,
                }
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string }
              - {
                  label: SmallText,
                  name: smalltext,
                  widget: string,
                  required: false,
                }
      - label: 'About'
        name: 'about'
        file: 'content/about.md'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about',
            }
          - { label: Page Title, name: title, widget: string }
          - label: Hero
            name: hero
            widget: object
            fields:
              - {
                  label: Background Color (hex),
                  name: background,
                  widget: string,
                }
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string }
          - label: Body
            name: body
            widget: markdown
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'content/_posts/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
